version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  #install:
    #commands:
      # - command
      # - command
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
      # - command
      # - command
  #post_build:
    #commands:
        - sudo apt-get install git -y
        - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
        - heroku create
        - git init
        - git add .
        - git config --global user.email "prem.nambi@gmail.com"
        - git config --global user.name "prem.nambi@gmail.com"
        - heroku git:remote -a still-beyond-24839
        - git push heroku master
        - echo "All success"
